name: Deploy Terraform (Matrix)

on:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region_folder: ["us-east-1", "eu-central-1"]

    defaults:
      run:
        working-directory: services/bu-logging/environments/log-archive/${{ matrix.region_folder }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.region_folder }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"